cc_binary(
        name = "delete_qualifier",
        srcs = ["delete_qualifier.cpp"],
        )

cc_binary(
        name = "singleton",
        srcs = ["singleton.cpp"],
        )

cc_binary(
        name = "interfaces",
        srcs = ["interfaces.cpp"],
        )

cc_binary(
        name = "mutable",
        srcs = ["mutable.cpp"],
        )

cc_binary(
        name = "name_hiding",
        srcs = ["name_hiding.cpp"],
        )

cc_binary(
        name = "virtual_destructor",
        srcs = ["virtual_destructor.cpp"],
        )
