cc_binary(
        name = "palindrome",
        srcs = ["palindrome.cpp"],
        )

cc_binary(
        name = "binary_search",
        srcs = ["binary_search.cpp"],
        )

cc_binary(
        name = "linked_list",
        srcs = ["linked_list.cpp"],
        )

cc_binary(
        name = "selection_sort",
        srcs = ["selection_sort.cpp"],
        )
