cc_binary(
        name = "all_of",
        srcs = ["all_of.cpp"],
        )

cc_binary(
        name = "none_of",
        srcs = ["none_of.cpp"],
        )

cc_binary(
        name = "any_of",
        srcs = ["any_of.cpp"],
        )

cc_binary(
        name = "mismatch",
        srcs = ["mismatch.cpp"],
        )

cc_binary(
        name = "count",
        srcs = ["count.cpp"],
        )

cc_binary(
        name = "count_if",
        srcs = ["count_if.cpp"],
        )

cc_binary(
        name = "equal",
        srcs = ["equal.cpp"],
        )

cc_binary(
        name = "for_each",
        srcs = ["for_each.cpp"],
        )

cc_binary(
        name = "for_each_n",
        srcs = ["for_each_n.cpp"],
        )

cc_binary(
        name = "copy",
        srcs = ["copy.cpp"],
        )
