cc_binary(
        name = "static_keyword",
        srcs = ["static_keyword.cpp"],
        )

cc_binary(
        name = "shared_unique_ptrs",
        srcs = ["shared_unique_ptrs.cpp"],
        )

cc_binary(
        name = "pointers_and_references",
        srcs = ["pointers_and_references.cpp"],
        )
