cc_binary(
        name = "static_keyword",
        srcs = ["static_keyword.cpp"],
        )

cc_binary(
        name = "interfaces",
        srcs = ["interfaces.cpp"],
        )

cc_binary(
        name = "shared_unique_ptrs",
        srcs = ["shared_unique_ptrs.cpp"],
        )

cc_binary(
        name = "pointers_and_references",
        srcs = ["pointers_and_references.cpp"],
        )

cc_binary(
        name = "typedef_alias",
        srcs = ["typedef_alias.cpp"],
        )

cc_binary(
        name = "enums",
        srcs = ["enums.cpp"],
        )

cc_binary(
        name = "tuples",
        srcs = ["tuples.cpp"],
        )
