cc_binary(
        name = "static_keyword",
        srcs = ["static_keyword.cpp"],
        )

cc_binary(
        name = "pointers_and_references",
        srcs = ["pointers_and_references.cpp"],
        )

cc_binary(
        name = "typedef_alias",
        srcs = ["typedef_alias.cpp"],
        )

cc_binary(
        name = "enums",
        srcs = ["enums.cpp"],
        )
