cc_binary(
        name = "lambdas_basics",
        srcs = ["lambdas_basics.cpp"],
        )

cc_binary(
        name = "typedef_alias",
        srcs = ["typedef_alias.cpp"],
        )

cc_binary(
        name = "enums",
        srcs = ["enums.cpp"],
        )

cc_binary(
        name = "tuples",
        srcs = ["tuples.cpp"],
        )

cc_binary(
        name = "structured_bindings",
        srcs = ["structured_bindings.cpp"],
        )
